### PR TITLE
Update for shift 2017

### PR DESCRIPTION
**Pull request by jsoverson**
Includes update to estraverse 4.2 and minimal dependency updates to ensure tests run.

There are a number of updates that could also be added to bring the repo up-to-date with modern practices but those are probably better in another PR.

### CODE REVIEW

**Comment by michaelficarra** [comment]
You should add some tests that show support for ES2017 features. Here's a helpful comparison: https://github.com/shapesecurity/shift-spec/compare/es6...es2017.

**Comment by jsoverson** [comment]
@michaelficarra shift-parser hasn't been released with es2017 support yet, it's still in a branch. This consumes the spec alone as part of its core dependencies. If tests need to be added then we have to wait for shift parser.

Parsing and traversal tests also mostly deal with everything.js. Are you planning on updating that for es2016 and es2017?

**Comment by michaelficarra** [comment]
@jsoverson Shift parser has recently added es2017 support, so that should no longer be a problem. As far as testing goes, we should definitely add some tests. Everything.js was a convenient way to do it, but we can also just write tailored tests here. I'm okay with either route: tests for just this project, or an update to everything.js.

**Comment by jsoverson** [comment]
I removed magic number tests and replaced them with assertions that shift-traverse traverses the same number of nodes that shift-reducer does and added a test for syntax introduced in 2016 (exponentiation), 2017 (async/await, trailing commas in params).

**Review by michaelficarra — APPROVED** [review]

**Comment by jsoverson** [comment]
I'm closing this and will maintain the updated project in the fork. I'll publish it as `shift-traverser`

**Pull request closed without merging**
